// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9FcqKkFTrFDozv-WjjmjhOWEYzFrLWCc',
    appId: '1:337820788025:web:f095ffc8fa8441f57b74e8',
    messagingSenderId: '337820788025',
    projectId: 'notes-a6002',
    authDomain: 'notes-a6002.firebaseapp.com',
    storageBucket: 'notes-a6002.appspot.com',
    measurementId: 'G-H3EVY9XZZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVsTORDGKR0w6jcyPH1ICxgDi7paVcOzs',
    appId: '1:337820788025:android:7cb97b25211f480e7b74e8',
    messagingSenderId: '337820788025',
    projectId: 'notes-a6002',
    storageBucket: 'notes-a6002.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Bplpga-BEaNZeykNPIvdPIdTgMOMA14',
    appId: '1:337820788025:ios:11ce761b3d1e723f7b74e8',
    messagingSenderId: '337820788025',
    projectId: 'notes-a6002',
    storageBucket: 'notes-a6002.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Bplpga-BEaNZeykNPIvdPIdTgMOMA14',
    appId: '1:337820788025:ios:11ce761b3d1e723f7b74e8',
    messagingSenderId: '337820788025',
    projectId: 'notes-a6002',
    storageBucket: 'notes-a6002.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9FcqKkFTrFDozv-WjjmjhOWEYzFrLWCc',
    appId: '1:337820788025:web:ca8e871e28b9a17b7b74e8',
    messagingSenderId: '337820788025',
    projectId: 'notes-a6002',
    authDomain: 'notes-a6002.firebaseapp.com',
    storageBucket: 'notes-a6002.appspot.com',
    measurementId: 'G-13ZY0EKKV5',
  );
}
